version: "3.8"

services:
  api:
    container_name: api
    build: ./api
    ports:
      - ${PROD_API_PORT}:${PROD_API_PORT}
  web:
    container_name: web
    build: ./web
    ports:
      - ${PROD_WEB_PORT}:80
  data:
    container_name: data
    build: ./mock/data
    ports:
      - ${PROD_MOCK_PORT}:4200
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mock/db:/data/db
